server:
  port: 8772
spring:
  application:
    name: sentinel-8772
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8090
feign:
  sentinel:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"