server:
  port: 8762
spring:
  application:
    name: eureka-client-8762 #服务名称

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/   #配置注册中心地址 http://replica1:8002/eureka/,http://replica2:8003/eureka/ #同时注册到两个注册中心
management:
  endpoints:
    web:
      exposure:
        include: "*"

