server:
  port: 8764
spring:
  application:
    name: eureka-client-openFeign-8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enable: true


