server:
  port: 8763
spring:
  application:
    name: eureka-client-8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

service:
  service1: eureka-client-8762

